#include "mcu/lpc822.h"
#include "mcu/mcu.h"

namespace mcu {

Mcu::Mcu() {
  EnablePeripheralClocks();
  ResetPeripherals();
}

void Mcu::EnablePeripheralClocks() {
  SYSCON->SYSAHBCLKCTRL |= SYSCON_SYSAHBCLKCTRL_GPIO(1U);
  SYSCON->SYSAHBCLKCTRL |= SYSCON_SYSAHBCLKCTRL_SWM(1U);
  SYSCON->SYSAHBCLKCTRL |= SYSCON_SYSAHBCLKCTRL_SCT(1U);
  SYSCON->SYSAHBCLKCTRL |= SYSCON_SYSAHBCLKCTRL_MRT(1U);
  SYSCON->SYSAHBCLKCTRL |= SYSCON_SYSAHBCLKCTRL_UART0(1U);
  SYSCON->SYSAHBCLKCTRL |= SYSCON_SYSAHBCLKCTRL_IOCON(1U);
  SYSCON->SYSAHBCLKCTRL |= SYSCON_SYSAHBCLKCTRL_ACMP(1U);
  SYSCON->SYSAHBCLKCTRL |= SYSCON_SYSAHBCLKCTRL_ADC(1U);
}

void Mcu::ResetPeripherals() {
  SYSCON->PRESETCTRL &= ~SYSCON_PRESETCTRL_GPIO_RST_N(1U);
  SYSCON->PRESETCTRL |= SYSCON_PRESETCTRL_GPIO_RST_N(1U);

  SYSCON->PRESETCTRL &= ~SYSCON_PRESETCTRL_SCT_RST_N(1U);
  SYSCON->PRESETCTRL |= SYSCON_PRESETCTRL_SCT_RST_N(1U);

  SYSCON->PRESETCTRL &= ~SYSCON_PRESETCTRL_MRT_RST_N(1U);
  SYSCON->PRESETCTRL |= SYSCON_PRESETCTRL_MRT_RST_N(1U);

  SYSCON->PRESETCTRL &= ~SYSCON_PRESETCTRL_UARTFRG_RST_N(1U);
  SYSCON->PRESETCTRL |=
      SYSCON_PRESETCTRL_UARTFRG_RST_N(1U);
  SYSCON->PRESETCTRL &= ~SYSCON_PRESETCTRL_UART0_RST_N(1U);
  SYSCON->PRESETCTRL |= SYSCON_PRESETCTRL_UART0_RST_N(1U);

  SYSCON->PRESETCTRL &= ~SYSCON_PRESETCTRL_ACMP_RST_N(1U);
  SYSCON->PRESETCTRL |= SYSCON_PRESETCTRL_ACMP_RST_N(1U);

  SYSCON->PRESETCTRL &= ~SYSCON_PRESETCTRL_ADC_RST_N(1U);
  SYSCON->PRESETCTRL |= SYSCON_PRESETCTRL_ADC_RST_N(1U);
}

}  // namespace mcu
